USE freshFeast_db;

INSERT INTO masterFood (foodName, foodType, foodCategory)
VALUES
("Artichoke", "vegetable", "flowers"),
("Arugula", "vegetable", "leaves"),
("Asparagus", "vegetable", "stems"),
("Green Beans",  "vegetable", "legumes"),
 ("Bamboo Chutes". "vegetable", "stems"), 
("Beets", "vegetable",  "roots"),
("Bok Choy", "vegetable", "leaves"),
("Fava Beans", "vegetable", "legumes"),
("Broccoli", "vegetable", "flowers"),
("Brussel Sprouts", "vegetable","leaves"),
("Cabbage", "vegetable", "leaves"),
("Carrots", "vegetable", "roots"),
("Cauliflower", "vegetable", "flowers"),
("Celery", "vegetable", "stems"),
("Collards", "vegetable", "leaves"),
("Corn", "vegetable", "fruit-type"),
("Cucumber", "vegetable", "fruit-type"),
("Edamame", "vegetable", "legumes"),
("Eggplants", "vegetable", "fruit-type"),
("Fennel", "vegetable", "bulbs"),
("Garlic", "vegetable", "bulbs"),
("Ginger", "vegetable", "roots"),
("Jicama", "vegetable", "roots"),
("Kale", "vegetable","leaves"),
("Leeks", "vegetable", "bulbs"),
("Lettuce", "vegetable", "leaves"),
("Mushrooms", "vegetable", "fungi"),
("Okra", "vegetable","fruit-type"),
("Onions", "vegetable", "bulbs"),
("Parsnips", "vegetable", "roots"),
("Green Peas", "vegetable", "legumes"),
("Red Peppers", "vegetable", "fruit-type"),
("Green Peppers", "vegetable", "fruit-type"),
("Yellow Peppers", "vegetable", "fruit-type"),
("Potatoes", "vegetable", "roots"),
("Pumpkins", "vegetable", "gourds"),
("Radishes", "vegetable", "roots"),
("Rutabagas", "vegetable", "roots"),
("Shallots", "vegetable", "bulbs"),
("Snow Peas", "vegetable", "legumes"),
("Spaghetti Squash", "vegetable", "gourds"),
("Spinach", "vegetable", "leaves"),
("Butternut Squash", "vegetable", "gourds"),
("Snap Peas", "vegetable", "legumes"),
("Sweet Potatoes", "vegetable", "tubers"),
("Swiss Chard", "vegetable", "leaves"),
("Tomatillos", "vegetable", "fruit-type"),
("Tomatoes", "vegetable", "fruit-type"),
("Truffles", "vegetable", "fungi"),
("Turnips", "vegetable", "roots"),
("Watercress", "vegetable", "leaves"),
("Yams", "vegetable", "roots"),
("Zucchinis", "vegetable", "fruit-type")






